# Generated by Django 3.2.9 on 2021-11-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
